# Generated by Django 3.0.8 on 2020-07-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('select_class', models.CharField(choices=[('JSS 1 ', 'JSS 1'), ('JSS 2', 'JSS 2'), ('JSS 3', 'JSS 3'), ('SSS 1', 'SSS 1'), ('SSS 2', 'SSS 2'), ('SSS 3', 'SSS 3')], max_length=120)),
                ('course_code', models.CharField(default='001', max_length=120)),
                ('slug', models.SlugField(default='', editable=False, max_length=120)),
                ('date_stamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('name', 'slug')},
            },
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
