# Generated by Django 3.0.8 on 2020-07-17 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200717_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='001', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='select_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Class'),
        ),
    ]
