# Generated by Django 3.0.8 on 2020-07-16 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='addmission_id',
            new_name='admission_id',
        ),
    ]
