# Generated by Django 3.0.8 on 2020-07-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200716_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='ward',
            field=models.ManyToManyField(blank=True, to='student.Student'),
        ),
    ]
