# Generated by Django 3.0.8 on 2020-07-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200716_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='parent',
            unique_together={('first_name', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('first_name', 'slug')},
        ),
    ]
