# Generated by Django 3.0.8 on 2020-07-17 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200717_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
