# Generated by Django 3.0.8 on 2020-07-17 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200717_1337'),
        ('student', '0005_student_date_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(default='Please Select Class *', null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Class'),
        ),
    ]
